# Generated by Django 4.2.17 on 2024-12-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
