# Generated by Django 4.2.17 on 2024-12-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_phonenumber_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='entered_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
