# Generated by Django 4.2.17 on 2024-12-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=8)),
                ('password2', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
