# Generated by Django 4.2.17 on 2024-12-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_signup_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='password',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password2',
            field=models.CharField(max_length=15),
        ),
    ]
