# Generated by Django 4.2.17 on 2024-12-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('buy', 'خرید یک ملک'), ('sell', 'فروش یک ملک'), ('rent', 'اجاره یک ملک')], default='buy', max_length=10, verbose_name='نوع ملک')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('contact_number', models.CharField(max_length=12, verbose_name='شماره تماس')),
                ('province', models.CharField(max_length=50, verbose_name='استان')),
                ('city', models.CharField(max_length=50, verbose_name='شهر/بخش')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='بودجه')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='متراژ')),
                ('amenities', models.TextField(max_length=200, verbose_name='امکانات')),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد اتاق خواب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت درخواست')),
            ],
        ),
    ]
