# Generated by Django 4.2.17 on 2024-12-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrequest',
            name='amenities',
            field=models.TextField(max_length=255, verbose_name='امکانات'),
        ),
    ]
