# Generated by Django 4.2.17 on 2024-12-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_propertyrequest_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental_Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('Apartment', 'اپارتمان'), ('commercial', 'تجاری'), ('villa', 'ویلا')], max_length=20, verbose_name='نوع ملک')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='متراژ')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='پول پیش')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ اجاره')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='حق کمیسیون')),
            ],
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=255, verbose_name='بودجه'),
        ),
    ]
