# Generated by Django 4.2.17 on 2024-12-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rental_property_amenities_rental_property_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_property',
            name='location_type',
            field=models.CharField(choices=[('Apartment', 'اپارتمان'), ('commercial', 'تجاری'), ('villa', 'ویلا')], max_length=20, verbose_name='موقعیت ملک شما'),
        ),
    ]
