# Generated by Django 4.2.17 on 2024-12-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_rental_property_location_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPropertyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('city_and_neighborhood', models.CharField(max_length=200, verbose_name='شهر و محله')),
                ('min_area', models.PositiveIntegerField(verbose_name='حداقل متراژ')),
                ('max_area', models.PositiveIntegerField(verbose_name='حداکثر متراژ')),
                ('min_deposit', models.PositiveIntegerField(verbose_name='حداقل پول پیش')),
                ('min_rent', models.PositiveIntegerField(verbose_name='حداقل پول اجاره')),
                ('family_members', models.PositiveIntegerField(verbose_name='تعداد افراد خانواده')),
            ],
            options={
                'verbose_name': 'درخواست اجاره ملک',
            },
        ),
        migrations.AlterModelOptions(
            name='propertyrequest',
            options={'verbose_name': 'درخواست خرید ملک'},
        ),
        migrations.AlterModelOptions(
            name='rental_property',
            options={'verbose_name': 'ملک برای اجاره'},
        ),
    ]
