# Generated by Django 4.2.17 on 2024-12-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_propertyrequest_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpropertyrequest',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد اتاق خواب'),
        ),
        migrations.AlterField(
            model_name='propertyrequest',
            name='amenities',
            field=models.TextField(max_length=255, null=True, verbose_name='امکانات'),
        ),
    ]
